In [2]:
import pandas as pd

In [3]:
import numpy as np

In [6]:
meusDados = np.matrix('1, 2, 3; 4, 5, 6; 7, 8, 9; 10, 11, 12')
meusDados

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [7]:
meuDF = pd.DataFrame(meusDados)
meuDF

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [8]:
type(meusDados)

numpy.matrix

In [9]:
indice = ['linha ' + str(i) for i in range(4)]

In [10]:
colunas = ['coluna ' + str(i) for i in range(3)]

In [11]:
df2 = pd.DataFrame(data=meusDados, index=indice, columns=colunas)
df2

coluna 0  coluna 1  coluna 2
linha 0         1         2         3
linha 1         4         5         6
linha 2         7         8         9
linha 3        10        11        12

In [12]:
df3 = {'Coluna0': {'linha0': 1, 'linha1': 4, 'linha2': 7},
       'Coluna1': {'linha0': 2, 'linha1': 5, 'linha2': 8},
       'Coluna2': {'linha0': 3, 'linha1': 6, 'linha2': 9}
}
df3

{'Coluna0': {'linha0': 1, 'linha1': 4, 'linha2': 7},
 'Coluna1': {'linha0': 2, 'linha1': 5, 'linha2': 8},
 'Coluna2': {'linha0': 3, 'linha1': 6, 'linha2': 9}}

In [13]:
df3 = pd.DataFrame(df3)
df3

Coluna0  Coluna1  Coluna2
linha0        1        2        3
linha1        4        5        6
linha2        7        8        9

In [14]:
df4 = pd.concat([meuDF, df2, df3])
df4

0     1     2  coluna 0  coluna 1  coluna 2  Coluna0  Coluna1  \
0         1.0   2.0   3.0       NaN       NaN       NaN      NaN      NaN   
1         4.0   5.0   6.0       NaN       NaN       NaN      NaN      NaN   
2         7.0   8.0   9.0       NaN       NaN       NaN      NaN      NaN   
3        10.0  11.0  12.0       NaN       NaN       NaN      NaN      NaN   
linha 0   NaN   NaN   NaN       1.0       2.0       3.0      NaN      NaN   
linha 1   NaN   NaN   NaN       4.0       5.0       6.0      NaN      NaN   
linha 2   NaN   NaN   NaN       7.0       8.0       9.0      NaN      NaN   
linha 3   NaN   NaN   NaN      10.0      11.0      12.0      NaN      NaN   
linha0    NaN   NaN   NaN       NaN       NaN       NaN      1.0      2.0   
linha1    NaN   NaN   NaN       NaN       NaN       NaN      4.0      5.0   
linha2    NaN   NaN   NaN       NaN       NaN       NaN      7.0      8.0   

         Coluna2  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
linha 0      NaN  
linha 1      NaN  
linha 2      NaN  
linha 3      NaN  
linha0       3.0  
linha1       6.0  
linha2       9.0

In [15]:
df4.isnull()  #para filtar valores nulos (retorna bool)

0      1      2  coluna 0  coluna 1  coluna 2  Coluna0  Coluna1  \
0        False  False  False      True      True      True     True     True   
1        False  False  False      True      True      True     True     True   
2        False  False  False      True      True      True     True     True   
3        False  False  False      True      True      True     True     True   
linha 0   True   True   True     False     False     False     True     True   
linha 1   True   True   True     False     False     False     True     True   
linha 2   True   True   True     False     False     False     True     True   
linha 3   True   True   True     False     False     False     True     True   
linha0    True   True   True      True      True      True    False    False   
linha1    True   True   True      True      True      True    False    False   
linha2    True   True   True      True      True      True    False    False   

         Coluna2  
0           True  
1           True  
2           True  
3           True  
linha 0     True  
linha 1     True  
linha 2     True  
linha 3     True  
linha0     False  
linha1     False  
linha2     False

In [16]:
df4.isnull().sum()

0           7
1           7
2           7
coluna 0    7
coluna 1    7
coluna 2    7
Coluna0     8
Coluna1     8
Coluna2     8
dtype: int64

In [18]:
df5 = df4.fillna(df4.mean())  #fillna é usado para preencher valores vazios. precisa passar os parâmetros entre parêntesis 
df5

0     1     2  coluna 0  coluna 1  coluna 2  Coluna0  Coluna1  \
0         1.0   2.0   3.0       5.5       6.5       7.5      4.0      5.0   
1         4.0   5.0   6.0       5.5       6.5       7.5      4.0      5.0   
2         7.0   8.0   9.0       5.5       6.5       7.5      4.0      5.0   
3        10.0  11.0  12.0       5.5       6.5       7.5      4.0      5.0   
linha 0   5.5   6.5   7.5       1.0       2.0       3.0      4.0      5.0   
linha 1   5.5   6.5   7.5       4.0       5.0       6.0      4.0      5.0   
linha 2   5.5   6.5   7.5       7.0       8.0       9.0      4.0      5.0   
linha 3   5.5   6.5   7.5      10.0      11.0      12.0      4.0      5.0   
linha0    5.5   6.5   7.5       5.5       6.5       7.5      1.0      2.0   
linha1    5.5   6.5   7.5       5.5       6.5       7.5      4.0      5.0   
linha2    5.5   6.5   7.5       5.5       6.5       7.5      7.0      8.0   

         Coluna2  
0            6.0  
1            6.0  
2            6.0  
3            6.0  
linha 0      6.0  
linha 1      6.0  
linha 2      6.0  
linha 3      6.0  
linha0       3.0  
linha1       6.0  
linha2       9.0

In [19]:
df8 = df5.copy()

In [21]:
df4.dropna(inplace=True)  #para apagar a linha onde tiver um índice vazio
df4

Empty DataFrame
Columns: [0, 1, 2, coluna 0, coluna 1, coluna 2, Coluna0, Coluna1, Coluna2]
Index: []

In [22]:
df5.dropna(subset=[1], inplace= True)
df5

0     1     2  coluna 0  coluna 1  coluna 2  Coluna0  Coluna1  \
0         1.0   2.0   3.0       5.5       6.5       7.5      4.0      5.0   
1         4.0   5.0   6.0       5.5       6.5       7.5      4.0      5.0   
2         7.0   8.0   9.0       5.5       6.5       7.5      4.0      5.0   
3        10.0  11.0  12.0       5.5       6.5       7.5      4.0      5.0   
linha 0   5.5   6.5   7.5       1.0       2.0       3.0      4.0      5.0   
linha 1   5.5   6.5   7.5       4.0       5.0       6.0      4.0      5.0   
linha 2   5.5   6.5   7.5       7.0       8.0       9.0      4.0      5.0   
linha 3   5.5   6.5   7.5      10.0      11.0      12.0      4.0      5.0   
linha0    5.5   6.5   7.5       5.5       6.5       7.5      1.0      2.0   
linha1    5.5   6.5   7.5       5.5       6.5       7.5      4.0      5.0   
linha2    5.5   6.5   7.5       5.5       6.5       7.5      7.0      8.0   

         Coluna2  
0            6.0  
1            6.0  
2            6.0  
3            6.0  
linha 0      6.0  
linha 1      6.0  
linha 2      6.0  
linha 3      6.0  
linha0       3.0  
linha1       6.0  
linha2       9.0

In [23]:
df6 = df5.drop(columns=['Coluna0'])
df6

0     1     2  coluna 0  coluna 1  coluna 2  Coluna1  Coluna2
0         1.0   2.0   3.0       5.5       6.5       7.5      5.0      6.0
1         4.0   5.0   6.0       5.5       6.5       7.5      5.0      6.0
2         7.0   8.0   9.0       5.5       6.5       7.5      5.0      6.0
3        10.0  11.0  12.0       5.5       6.5       7.5      5.0      6.0
linha 0   5.5   6.5   7.5       1.0       2.0       3.0      5.0      6.0
linha 1   5.5   6.5   7.5       4.0       5.0       6.0      5.0      6.0
linha 2   5.5   6.5   7.5       7.0       8.0       9.0      5.0      6.0
linha 3   5.5   6.5   7.5      10.0      11.0      12.0      5.0      6.0
linha0    5.5   6.5   7.5       5.5       6.5       7.5      2.0      3.0
linha1    5.5   6.5   7.5       5.5       6.5       7.5      5.0      6.0
linha2    5.5   6.5   7.5       5.5       6.5       7.5      8.0      9.0

In [24]:
df7 = df6.drop(index = [2])
df7

0     1     2  coluna 0  coluna 1  coluna 2  Coluna1  Coluna2
0         1.0   2.0   3.0       5.5       6.5       7.5      5.0      6.0
1         4.0   5.0   6.0       5.5       6.5       7.5      5.0      6.0
3        10.0  11.0  12.0       5.5       6.5       7.5      5.0      6.0
linha 0   5.5   6.5   7.5       1.0       2.0       3.0      5.0      6.0
linha 1   5.5   6.5   7.5       4.0       5.0       6.0      5.0      6.0
linha 2   5.5   6.5   7.5       7.0       8.0       9.0      5.0      6.0
linha 3   5.5   6.5   7.5      10.0      11.0      12.0      5.0      6.0
linha0    5.5   6.5   7.5       5.5       6.5       7.5      2.0      3.0
linha1    5.5   6.5   7.5       5.5       6.5       7.5      5.0      6.0
linha2    5.5   6.5   7.5       5.5       6.5       7.5      8.0      9.0

In [25]:
df5.Coluna2.unique()  #para pegar valores repetidos

array([6., 3., 9.])

In [26]:
df5.columns.unique()

Index([0, 1, 2, 'coluna 0', 'coluna 1', 'coluna 2', 'Coluna0', 'Coluna1',
       'Coluna2'],
      dtype='object')

In [27]:
df5.index.unique()

Index([        0,         1,         2,         3, 'linha 0', 'linha 1',
       'linha 2', 'linha 3',  'linha0',  'linha1',  'linha2'],
      dtype='object')

In [28]:
print(df5.Coluna2.unique())

[6. 3. 9.]


In [31]:
print(df5.columns.unique())

Index([0, 1, 2, 'coluna 0', 'coluna 1', 'coluna 2', 'Coluna0', 'Coluna1',
       'Coluna2'],
      dtype='object')


In [30]:
print(df5.index.unique())

Index([        0,         1,         2,         3, 'linha 0', 'linha 1',
       'linha 2', 'linha 3',  'linha0',  'linha1',  'linha2'],
      dtype='object')


In [33]:
df8.sort_values(by = 'Coluna1')  #para ordenar valores da coluna

0     1     2  coluna 0  coluna 1  coluna 2  Coluna0  Coluna1  \
linha0    5.5   6.5   7.5       5.5       6.5       7.5      1.0      2.0   
0         1.0   2.0   3.0       5.5       6.5       7.5      4.0      5.0   
1         4.0   5.0   6.0       5.5       6.5       7.5      4.0      5.0   
2         7.0   8.0   9.0       5.5       6.5       7.5      4.0      5.0   
3        10.0  11.0  12.0       5.5       6.5       7.5      4.0      5.0   
linha 0   5.5   6.5   7.5       1.0       2.0       3.0      4.0      5.0   
linha 1   5.5   6.5   7.5       4.0       5.0       6.0      4.0      5.0   
linha 2   5.5   6.5   7.5       7.0       8.0       9.0      4.0      5.0   
linha 3   5.5   6.5   7.5      10.0      11.0      12.0      4.0      5.0   
linha1    5.5   6.5   7.5       5.5       6.5       7.5      4.0      5.0   
linha2    5.5   6.5   7.5       5.5       6.5       7.5      7.0      8.0   

         Coluna2  
linha0       3.0  
0            6.0  
1            6.0  
2            6.0  
3            6.0  
linha 0      6.0  
linha 1      6.0  
linha 2      6.0  
linha 3      6.0  
linha1       6.0  
linha2       9.0

In [35]:
df8.rename(columns= {'Coluna1': 'COLUNA 1'}, inplace = True)
df8 

0     1     2  coluna 0  coluna 1  coluna 2  Coluna0  COLUNA 1  \
0         1.0   2.0   3.0       5.5       6.5       7.5      4.0       5.0   
1         4.0   5.0   6.0       5.5       6.5       7.5      4.0       5.0   
2         7.0   8.0   9.0       5.5       6.5       7.5      4.0       5.0   
3        10.0  11.0  12.0       5.5       6.5       7.5      4.0       5.0   
linha 0   5.5   6.5   7.5       1.0       2.0       3.0      4.0       5.0   
linha 1   5.5   6.5   7.5       4.0       5.0       6.0      4.0       5.0   
linha 2   5.5   6.5   7.5       7.0       8.0       9.0      4.0       5.0   
linha 3   5.5   6.5   7.5      10.0      11.0      12.0      4.0       5.0   
linha0    5.5   6.5   7.5       5.5       6.5       7.5      1.0       2.0   
linha1    5.5   6.5   7.5       5.5       6.5       7.5      4.0       5.0   
linha2    5.5   6.5   7.5       5.5       6.5       7.5      7.0       8.0   

         Coluna2  
0            6.0  
1            6.0  
2            6.0  
3            6.0  
linha 0      6.0  
linha 1      6.0  
linha 2      6.0  
linha 3      6.0  
linha0       3.0  
linha1       6.0  
linha2       9.0